[gag gdrive]
type = drive
client_id = 140844805228-fvn6vjkkg8cocb6sn05002e4lkdmtjlh.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0AeXRPp7KxglTq9N0zeAAcIpWNOdEZxd4Gy3SambZ8a0pacIPDFsKYCR2yGwwhlfg3eYk_Es8jSl_vbw-oxdGxO18BR168YoCdFuCAemdyqiNsfWqOyup5H1IapWDFnnxBwCgrj1MkpeGCAp5GP566YvitYuCwfT3DFDD1j3jaCgYKARYSARASFQHGX2MiJaxMrYVHW-EUd2BkmYlRLQ0175","token_type":"Bearer","refresh_token":"1//0c8uH5csOjwpeCgYIARAAGAwSNwF-L9Ir5k7xJo2NRQBYW6vv2A9yeTCtV6N79JP4dMfEDSk-AvWv5KVkn56L8ildiPPgKjg9v0Y","expiry":"2025-03-30T19:19:21.925015237+03:00"}
team_drive =

[gag gdrive real]
type = drive
client_id = 140844805228-fvn6vjkkg8cocb6sn05002e4lkdmtjlh.apps.googleusercontent.com
client_secret = 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
scope = drive

[seafile]
type = seafile
url = https://seafile.ingvarruulib.com
user = ingvar@saarend.com
pass = 5UkLKaPtHn96TW9caxuK1MSvCI77j7_odfOkw44
library = main
